service: photoApp

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

plugins:
  - serverless-iam-roles-per-function

functions:
# create data
  createCertificate:
    handler: api/create.certificate
    environment : 
      CERTIFICATE_TABLE_NAME : certificateTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED : 1
    iamRoleStatements :
      - Effect : "Allow"
        Action :
          - "dynamodb:PutItem"
        Resource: !GetAtt certificateTable.Arn
    events:
      - http:
          path: certificateList
          method: post
          cors:
            origin : "*"
            headers : ${self.custom.allowedHeaders}

# get user specific data
  getUserSpecificData:
    handler: api/userData.certificate
    environment : 
      CERTIFICATE_TABLE_NAME : certificateTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED : 1
    iamRoleStatements :
      - Effect : "Allow"
        Action :
          - "dynamodb:Scan"
        Resource: !GetAtt certificateTable.Arn
    events:
      - http:
          path: certificateList
          method: get
          cors:
            origin : "*"
            headers : ${self.custom.allowedHeaders}

resources:
  Resources:
    certificateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName : certificateTable
        BillingMode : PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName : certificate_id
            AttributeType : S
        KeySchema:
          - AttributeName : certificate_id
            KeyType : HASH